[package]
name = "challenge"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {  version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
log = "0.4.27"
env_logger = "0.11.8"
rand = "0.9.2"
